version: "3.8"

services:
  corti:
    image: ghcr.io/masha-el/corti-bot:latest
    container_name: corti
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./credentials:/app/credentials
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"